### PR TITLE
fixed typos of regsiter and PojoProducer.getProcucers

### LINKED ISSUE #326: typos need to be fixed
There are some obvious typos in the code that need to be fixed. e.g. resiter -> register, getProcucers -> getProducers.

### PR DESCRIPTION
**Pull request by yhj7727**
fixed #326

### CODE REVIEW

File: providers/provider-pojo/src/main/java/io/servicecomb/provider/pojo/schema/PojoProducers.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public void registerPojoProducer(PojoProducerMeta pojoProducer) {
     pojoMgr.register(pojoProducer.getSchemaId(), pojoProducer);
   }
 
-  public Collection<PojoProducerMeta> getProcucers() {
```
Comment (WillemJiang) [inline providers/provider-pojo/src/main/java/io/servicecomb/provider/pojo/schema/PojoProducers.java]: This is public method , we need to deprecated this method first and add new updated method for it.

Comment (yhj7727) [reply providers/provider-pojo/src/main/java/io/servicecomb/provider/pojo/schema/PojoProducers.java]: already added it back
